#!/bin/sh

cd ../../..
utils/RemoveSpace/RemoveSpace.mac src/IOL.cn/IOL9/dxIOL9CN.tex src/IOL.cn/IOL9/IOL9.tex src/IOL.cn/IOL9/IOL9.nospace.tex 
cd src/IOL.cn/IOL9

rm *.pdf

cp ../font-selector.tex ./

xelatex -shell-escape iol-2011-indiv-prob.cn.tex
xelatex -shell-escape iol-2011-indiv-solu.cn.tex
xelatex -shell-escape iol-2011-team-prob.cn.tex
xelatex -shell-escape iol-2011-team-solu.cn.tex

rm *.aux
rm *.log

mv *.pdf ../../../PDFs/